# Site settings
title: Happy departure station
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Happy World
user_description: 希望能够带给你快乐
user_title: by liuhappy
email: 3061228572@qq.com
# github_username:  liuhappy589
#腾讯qq_username:  你要开心。
exclude: ['package.json', 'src' , 'node_modules']
